"""
Training data for Vector expense app NLU models.
Intents + entity-annotated examples tailored to the app's 12 categories
and transaction schema (description, amount, category, date, type, cardId).
"""

# ---------------------------------------------------------------------------
# Intent definitions with example utterances
# ---------------------------------------------------------------------------

INTENT_EXAMPLES = {
    # --- count_transactions: "how many X?" ---
    "count_transactions": [
        "how many transactions do I have",
        "how many swiggy transactions",
        "how many times did I order from zomato",
        "count amazon orders",
        "number of uber rides",
        "how many payments to netflix",
        "total number of transactions",
        "how many food transactions",
        "how many shopping transactions this month",
        "how many debit transactions",
        "how many credit transactions",
        "count my grocery purchases",
        "how many times did I pay rent",
        "number of swiggy orders last month",
        "how many flipkart orders",
        "count my entertainment expenses",
        "how many fuel payments",
        "how many ola rides this week",
        "how many transactions in january",
        "count transactions above 500",
        "how many transactions below 100",
        "how many transactions on my hdfc card",
        "count transactions for this card",
        "how many times I ordered from starbucks",
        "number of dining transactions",
        "how many transfers did I make",
        "count my upi payments",
        "how many times did I pay electricity bill",
        "number of medical expenses",
        "how many travel bookings",
        "how many sbi card transactions",
        "count icici card orders",
        "how many transactions on my axis card",
        "how many swiggy orders on sbi card",
        "count amazon transactions in hdfc card",
        "how many swiggy orders in january on sbi card",
        "count uber rides last month with hdfc card",
        "how many sbi card transactions last month",
        "count hdfc card transactions this week",
        "how many food transactions on sbi card",
        "count transactions above 500 on hdfc card",
        "how many grocery transactions on icici card this month",
        "how many swiggy orders above 200 on sbi card",
    ],

    # --- total_spent: "how much did I spend on X?" ---
    "total_spent": [
        "how much did I spend",
        "how much did I spend on swiggy",
        "total spent on food",
        "how much money spent on shopping",
        "what is my total spending",
        "how much spent on zomato this month",
        "total amount spent on groceries",
        "how much did I spend on uber",
        "total food expenses",
        "how much on entertainment",
        "total transportation cost",
        "how much did I spend last month",
        "what is my total expenditure",
        "how much money did I spend on travel",
        "total spent on amazon",
        "how much on bills and utilities",
        "total education expenses",
        "sum of all my transactions",
        "what did I spend on health",
        "how much spent on netflix subscription",
        "total shopping spend this month",
        "total debits this month",
        "how much went to investments",
        "how much did I spend on fuel",
        "total restaurant expenses",
        "how much spent on coffee",
        "total amount on flipkart",
        "how much did I pay for insurance",
        "sum of grocery purchases",
        "total spending on my sbi card",
        "how much did I spend on hdfc card",
        "total spent on icici credit card",
        "how much on my axis card",
        "how much on swiggy in sbi card",
        "total zomato spending on hdfc card",
        "how much on swiggy in january with sbi card",
        "total zomato spending last month from hdfc card",
        "total spent on sbi card last month",
        "how much on hdfc card this week",
        "total food spending on icici card",
        "total spent above 1000 on sbi card",
        "total food expenses on hdfc card this month",
        "how much on swiggy above 500 from sbi card",
    ],

    # --- transactions_on_date: "what did I spend on X date?" ---
    "transactions_on_date": [
        "what did I spend yesterday",
        "show transactions from today",
        "what did I buy today",
        "transactions on march 5",
        "what did I spend on monday",
        "show me yesterday's expenses",
        "what happened on february 14",
        "list transactions from last friday",
        "show my spending for today",
        "what purchases did I make on 1st march",
        "transactions from the 15th",
        "what did I buy on january 26",
        "spending on christmas day",
        "show me december 31 transactions",
        "what did I spend 3 days ago",
        "transactions from last saturday",
        "show purchases from feb 28",
        "what did I buy this morning",
        "expenses on diwali",
        "transactions for march 1st",
        "sbi card transactions yesterday",
        "what did I spend on hdfc card today",
        "swiggy orders yesterday on sbi card",
        "show uber transactions today on hdfc card",
        "food transactions yesterday on icici card",
        "shopping expenses today on axis card",
        "transactions above 500 yesterday on sbi card",
        "what were my spends on 10th february",
        "anything charged on tuesday last week",
        "did I pay for anything on jan 2",
        "show me what I bought two days ago",
        "amazon purchases on march 12 on hdfc card",
        "how much did I spend last wednesday",
        "any transactions on new year's eve",
        "grocery expenses from last sunday on icici card",
        "payments made on the 20th of january",
        "what went out on 5th jan on axis card",
        "zomato orders from last thursday",
        "show all debits on feb 14 on sbi card",
        "did anything get charged the day before yesterday",
    ],

    # --- category_spend: "how much on category X?" ---
    "category_spend": [
        "how much did I spend on food and dining",
        "show my grocery spending",
        "what is my shopping expense",
        "transportation costs breakdown",
        "entertainment spending",
        "health and medical expenses",
        "utility bill total",
        "travel expenses this month",
        "education costs",
        "finance and investment outflow",
        "transfer amounts",
        "break down my food spending",
        "category wise spending",
        "which category did I spend most on",
        "top spending category",
        "show spending by category",
        "food vs shopping comparison",
        "monthly category breakdown",
        "what percentage is food",
        "dining expenses this month",
        "hdfc card food spending",
        "sbi card shopping expenses",
        "category breakdown for sbi card",
        "food spending on hdfc card this month",
        "shopping expenses on icici card last month",
        "food expenses above 500 on sbi card",
        "swiggy food spending on hdfc card",
        "how much went to utilities and bills last month",
        "what did I spend on education this year on axis card",
        "show me my travel spending compared to last month",
        "how much have I transferred in total",
        "what percentage of my spending is entertainment",
        "break down transportation vs travel expenses",
        "any health and medical bills on icici card this month",
        "how much am I spending on groceries each month",
        "other category expenses on hdfc card last month",
        "education fees on sbi card above 10000",
        "is my utility spending going up or down",
        "total transfers on axis card this month",
        "what did I blow on entertainment last weekend",
    ],

    # --- list_transactions: "show me / list transactions" ---
    "list_transactions": [
        "show my transactions",
        "list all transactions",
        "show recent transactions",
        "what are my latest expenses",
        "show me all swiggy orders",
        "list zomato transactions",
        "show shopping transactions",
        "list food expenses",
        "show all debits",
        "list credits",
        "show transactions above 1000",
        "list transactions below 200",
        "show last 10 transactions",
        "recent purchases",
        "show my expenses",
        "list all payments",
        "display my transactions",
        "show everything I bought",
        "list all orders from amazon",
        "show uber transactions",
        "show sbi card transactions",
        "list hdfc card expenses",
        "show transactions on my kotak card",
        "my swiggy transactions in sbi card",
        "show uber rides on hdfc card",
        "amazon orders from my icici card",
        "my swiggy transactions in january with sbi card",
        "show amazon orders last month from hdfc card",
        "show sbi card transactions this month",
        "list hdfc card expenses last week",
        "show food transactions on icici card",
        "list sbi card transactions above 1000",
        "show shopping transactions on hdfc card this month",
        "pull up my netflix transactions",
        "get me all flipkart orders from last month",
        "what do I have from blinkit this week",
        "show ola rides above 500",
        "any transactions between 200 and 1000",
        "lemme see my entertainment expenses on kotak card",
        "list all blinkit and swiggy transactions in february",
    ],

    # --- highest_transaction: "what was my biggest expense?" ---
    "highest_transaction": [
        "what was my biggest expense",
        "largest transaction",
        "most expensive purchase",
        "highest amount spent",
        "what is the biggest payment",
        "show my largest spending",
        "max transaction amount",
        "biggest food expense",
        "highest shopping purchase",
        "most expensive order",
        "largest debit",
        "what was my highest spend this month",
        "biggest transaction last month",
        "maximum amount I paid",
        "top transaction",
        "biggest expense on hdfc card",
        "largest sbi card transaction",
        "biggest swiggy order on sbi card",
        "biggest swiggy order in january with hdfc card",
        "biggest sbi card expense last month",
        "highest food expense on hdfc card",
        "most expensive swiggy order on sbi card",
        "biggest shopping expense on icici card this month",
        "costliest purchase this month",
        "priciest order on zomato",
        "what was the peak spending last week",
        "top expense on amazon this month",
        "which transaction was the largest on my hdfc card in february",
        "max grocery expense on sbi card",
        "my most expensive uber ride",
        "biggest flipkart order this year",
        "what did I spend the most on last month",
        "highest netflix payment on icici card",
        "show me the costliest dining expense",
        "largest entertainment spend this month",
        "priciest travel expense on hdfc card last month",
        "which was the most I ever paid on zomato with sbi card",
        "whats my biggest grocery bill",
        "top spending on amazon in march with icici card",
        "highest amount I dropped on a single transaction",
    ],

    # --- lowest_transaction: "what was my smallest expense?" ---
    "lowest_transaction": [
        "what was my smallest expense",
        "lowest transaction",
        "cheapest purchase",
        "minimum amount spent",
        "smallest payment",
        "least expensive transaction",
        "minimum spending",
        "smallest debit",
        "what is the lowest amount I spent",
        "cheapest order",
        "smallest transaction on sbi card",
        "smallest sbi card transaction last month",
        "cheapest uber ride on hdfc card",
        "lowest food expense on icici card",
        "smallest swiggy order on sbi card this month",
        "cheapest grocery purchase on hdfc card last month",
        "lowest transaction under 100 on axis card",
        "cheapest zomato order under 200 on sbi card",
        "what was the tiniest purchase on my kotak card",
        "most affordable transaction last week",
        "show me my least expensive order on amex card",
        "smallest amazon purchase this month",
        "what's the lowest amount I paid on hdfc card last month",
        "cheapest netflix charge on icici card",
        "minimum transaction on axis card in january",
        "tiniest expense on sbi card yesterday",
        "least expensive grocery order on kotak card",
        "lowest ola ride fare on hdfc card this month",
        "smallest blinkit order on sbi card",
        "what was my cheapest starbucks purchase",
        "most affordable shopping transaction on amex card last month",
        "lowest entertainment expense on icici card",
        "smallest health related transaction under 500",
        "cheapest flipkart order on axis card this month",
        "minimum amount paid on kotak card last week",
        "what's the least I spent on transportation",
        "tiniest food expense on hdfc card in february",
        "show me the smallest transaction under 50",
        "lowest spending on my sbi card this week",
        "cheapest purchase I made yesterday on icici card",
    ],

    # --- average_spend: "what is my average spending?" ---
    "average_spend": [
        "what is my average spending",
        "average transaction amount",
        "mean spending per transaction",
        "average food expense",
        "what do I usually spend",
        "average daily spending",
        "average monthly expenditure",
        "mean amount per order",
        "average grocery bill",
        "what is my typical spend",
        "average shopping expense",
        "per transaction average",
        "average uber ride cost",
        "mean expense amount",
        "average spending on swiggy",
        "average spend on hdfc card",
        "average icici card transaction",
        "average swiggy order on sbi card",
        "average spending on sbi card last month",
        "average food expense on hdfc card",
        "average swiggy spend on icici card this month",
        "average grocery spending on axis card last month",
        "average uber ride above 100 on sbi card",
        "how much do I normally spend on zomato",
        "what's my usual amazon order amount",
        "typical flipkart purchase amount",
        "mean netflix charge per month",
        "average blinkit order cost",
        "what's the normal spend on entertainment",
        "average travel expense this month",
        "how much do I usually spend on dining",
        "average health spending on kotak card",
        "typical education expense on amex card",
        "per-transaction average on rbl card",
        "usual utility bill amount last month",
        "average ola ride cost this week",
        "what do I typically spend at starbucks",
        "mean spending on groceries in february",
        "average entertainment expense on axis card last week",
        "how much is my normal monthly spend on food",
    ],

    # --- monthly_summary: "how was my spending this month?" ---
    "monthly_summary": [
        "how was my spending this month",
        "monthly summary",
        "this month overview",
        "show me this month's report",
        "monthly spending report",
        "how did I spend in february",
        "january spending summary",
        "give me a monthly breakdown",
        "this month's expenses summary",
        "spending overview for march",
        "last month summary",
        "month to date spending",
        "compare this month vs last month",
        "how is my spending trend",
        "monthly expense report",
        "monthly summary for sbi card",
        "hdfc card monthly spending",
        "sbi card swiggy monthly summary",
        "hdfc card food spending monthly",
        "monthly swiggy spending on sbi card in january",
        "monthly food spending on hdfc card last month",
        "give me a recap of april spending",
        "spending snapshot for may",
        "how am I doing this month financially",
        "review my june expenses",
        "show me a breakdown of july spending",
        "august expense analysis",
        "september spending overview on icici card",
        "axis card monthly recap",
        "kotak card spending summary for october",
        "amex card monthly expense overview",
        "how does this month compare to previous months",
        "spending trend over the last few months",
        "november grocery spending summary",
        "december shopping expenses breakdown",
        "monthly entertainment spending report",
        "travel expenses this month on axis card",
        "amazon spending recap for november on kotak card",
        "zomato monthly summary on amex card",
        "what does my monthly spending look like so far",
    ],

    # --- compare_months: month-over-month comparisons ---
    "compare_months": [
        "did I spend more this month vs last month",
        "compare january and february spending",
        "how does this month compare to last",
        "was last month more expensive",
        "month over month spending comparison",
        "am I spending more or less than last month",
        "spending difference between this month and last",
        "which month did I spend more",
        "compare my spending across months",
        "how much more did I spend this month",
        "did my spending go up this month",
        "is my spending increasing month to month",
        "how does my spending trend look",
        "compare last two months spending",
        "month on month comparison",
        "spending this month compared to previous month",
        "am I doing better or worse than last month",
        "show me a month to month comparison",
        "how does february compare to january",
        "march vs april spending",
        "is my spending going up or down",
        "compare my monthly totals",
        "which month was more expensive",
        "how does this month stack up against last",
        "monthly spending comparison",
        "have I been spending more lately",
        "did my expenses go up compared to last month",
        "compare my last two months",
        "spending trend this month vs last",
        "am I spending more each month",
        "how much did my spending change this month",
        "month over month change in spending",
        "compare this month to the one before",
        "did I cut down spending this month",
        "is my spending higher or lower this month",
        "compare food spending this month vs last",
        "how does grocery spending compare month to month",
    ],

    # --- top_category: where does money go ---
    "top_category": [
        "what is my biggest spending category",
        "where do I spend the most",
        "which category gets most of my money",
        "top 3 expense categories",
        "what takes up most of my budget",
        "show me my top spending areas",
        "where does my money go",
        "what are my biggest expenses by category",
        "which category do I spend the most on",
        "top spending categories",
        "what category is eating my money",
        "show my highest spending categories",
        "where am I spending the most money",
        "rank my spending by category",
        "what are my top expenses",
        "main spending areas",
        "biggest expense category",
        "which areas do I spend the most in",
        "top 5 spending categories",
        "where is most of my money going",
        "what dominates my spending",
        "primary spending categories",
        "show me where I spend most",
        "what are my main expenses",
        "breakdown of top expenses",
        "leading spending categories",
        "what costs me the most",
        "top expense areas this month",
        "which categories are draining my wallet",
        "biggest spending buckets",
        "where should I cut back",
        "what are my highest categories",
        "rank my expenses",
        "show top categories on hdfc card",
        "top spending categories this month",
        "where does most money go on sbi card",
        "biggest categories last month",
    ],

    # --- spending_health: budget awareness / overspending concerns ---
    "spending_health": [
        "am I spending too much",
        "how is my budget doing",
        "am I overspending on food",
        "is my spending normal",
        "am I within my budget",
        "should I be worried about my spending",
        "am I being financially responsible",
        "is my spending out of control",
        "how healthy is my spending",
        "am I on track with my budget",
        "spending health check",
        "how are my finances looking",
        "am I spending wisely",
        "is my spending sustainable",
        "financial health overview",
        "am I saving enough",
        "do I need to cut back",
        "is my spending pattern healthy",
        "how does my spending look overall",
        "am I in good financial shape",
        "spending habits assessment",
        "am I overspending",
        "review my spending habits",
        "how disciplined is my spending",
        "am I burning through money too fast",
        "is my spending getting out of hand",
        "should I be spending less",
        "rate my spending",
        "how frugal am I being",
        "is my expense level reasonable",
        "give me a spending health score",
        "am I spending more than I should",
        "evaluate my expenses",
        "am I living within my means",
        "check my financial health",
        "how am I doing financially",
        "is my food spending too high",
    ],

    # --- frequent_merchant: most-visited merchants ---
    "frequent_merchant": [
        "where do I shop most often",
        "which app do I order from most",
        "most visited merchant",
        "my top merchants",
        "who gets most of my money",
        "which store do I buy from the most",
        "most frequent transactions",
        "where do I keep spending money",
        "show my most visited stores",
        "top merchants by frequency",
        "which places do I go to the most",
        "my favorite merchants",
        "most common transactions",
        "where do I transact the most",
        "which merchants come up most often",
        "frequent shopping destinations",
        "top places I spend at",
        "show me my regular merchants",
        "where am I a regular customer",
        "which services do I use most",
        "most frequent purchases from where",
        "my go to merchants",
        "recurring merchants",
        "top 5 merchants",
        "which shops do I visit most",
        "where do I order from the most",
        "most used services",
        "frequent vendors",
        "show my top 10 merchants",
        "which merchants do I frequent",
        "stores I shop at most often",
        "where do I spend most frequently",
        "my most visited places",
        "top merchants this month",
        "which app gets most of my orders",
        "frequent merchants on hdfc card",
        "top merchants on sbi card this month",
    ],

    # --- unusual_spend: anomaly detection ---
    "unusual_spend": [
        "any unusual transactions",
        "show large unexpected charges",
        "anything look suspicious",
        "big transactions I might have missed",
        "any outlier expenses",
        "transactions that seem off",
        "suspicious activity on my account",
        "any charges I should be worried about",
        "large or unusual purchases",
        "did I get charged for something weird",
        "show me abnormal spending",
        "any unexpected payments",
        "flag unusual expenses",
        "are there any red flags in my spending",
        "weird transactions",
        "charges that don't look right",
        "any anomalies in my spending",
        "unusually high transactions",
        "anything out of the ordinary",
        "surprising charges",
        "show me spending outliers",
        "transactions I should double check",
        "anything that looks fraudulent",
        "unexpected large payments",
        "show me unusual activity",
        "any charges I don't recognize",
        "big unexpected expenses",
        "weird or suspicious charges",
        "flagged transactions",
        "any spending anomalies this month",
        "transactions that stand out",
        "show me the outliers",
        "abnormally large purchases",
        "any surprise charges",
        "did anything unusual happen on my account",
        "unusual transactions on hdfc card",
        "any suspicious charges on sbi card",
    ],

    # --- weekly_summary: weekly reports ---
    "weekly_summary": [
        "how was this week",
        "weekly spending report",
        "what did I spend this week",
        "weekly breakdown",
        "this week's expenses",
        "show me the week summary",
        "how much did I spend this week",
        "weekly expense report",
        "spending this week so far",
        "week in review",
        "weekly financial summary",
        "how is this week looking",
        "show me this week's spending",
        "weekly recap",
        "how much have I spent this week",
        "what did this week cost me",
        "spending report for this week",
        "weekly spending overview",
        "break down this week's expenses",
        "this week's transactions",
        "how did I do this week",
        "weekly spending total",
        "what have I spent since monday",
        "spending since the start of the week",
        "last 7 days spending",
        "past week expenses",
        "show my last 7 days",
        "how was last week",
        "last week's spending summary",
        "weekly overview",
        "daily breakdown for this week",
        "day by day spending this week",
        "what does this week look like",
        "weekly spending on food",
        "this week's grocery expenses",
        "weekly spending on hdfc card",
        "how much on sbi card this week",
    ],
}

# ---------------------------------------------------------------------------
# Entity-annotated training data for NER
# Format: (text, [(start, end, entity_type), ...])
# ---------------------------------------------------------------------------

ENTITY_EXAMPLES = [
    # merchant entities
    ("how many swiggy transactions", [(9, 15, "MERCHANT")]),
    ("total spent on zomato", [(15, 21, "MERCHANT")]),
    ("count amazon orders", [(6, 12, "MERCHANT")]),
    ("show uber transactions", [(5, 9, "MERCHANT")]),
    ("how much on netflix", [(12, 19, "MERCHANT")]),
    ("list flipkart purchases", [(5, 13, "MERCHANT")]),
    ("how many ola rides", [(9, 12, "MERCHANT")]),
    ("starbucks expenses", [(0, 9, "MERCHANT")]),
    ("total myntra spending", [(6, 12, "MERCHANT")]),
    ("bigbasket orders this month", [(0, 9, "MERCHANT")]),
    ("how much did I spend on spotify", [(24, 31, "MERCHANT")]),
    ("payments to airtel", [(12, 18, "MERCHANT")]),
    ("blinkit delivery charges", [(0, 7, "MERCHANT")]),
    ("makemytrip bookings", [(0, 10, "MERCHANT")]),
    ("zerodha transactions", [(0, 7, "MERCHANT")]),
    ("rapido ride expenses", [(0, 6, "MERCHANT")]),
    ("irctc ticket bookings", [(0, 5, "MERCHANT")]),
    ("hotstar subscription", [(0, 7, "MERCHANT")]),
    ("pharmeasy orders", [(0, 9, "MERCHANT")]),
    ("jio recharge payments", [(0, 3, "MERCHANT")]),

    # category entities
    ("how much on food and dining", [(12, 27, "CATEGORY")]),
    ("total grocery spending", [(6, 13, "CATEGORY")]),
    ("shopping expenses", [(0, 8, "CATEGORY")]),
    ("transportation costs", [(0, 14, "CATEGORY")]),
    ("entertainment spending", [(0, 13, "CATEGORY")]),
    ("health and medical bills", [(0, 18, "CATEGORY")]),
    ("utility expenses", [(0, 7, "CATEGORY")]),
    ("travel costs this month", [(0, 6, "CATEGORY")]),
    ("education fees", [(0, 9, "CATEGORY")]),
    ("investment outflow", [(0, 10, "CATEGORY")]),
    ("how much on groceries", [(12, 21, "CATEGORY")]),
    ("total food expenses", [(6, 10, "CATEGORY")]),
    ("show dining transactions", [(5, 11, "CATEGORY")]),
    ("medical bill total", [(0, 7, "CATEGORY")]),
    ("fuel expenses", [(0, 4, "CATEGORY")]),

    # date entities
    ("transactions from yesterday", [(18, 27, "DATE")]),
    ("what did I spend today", [(17, 22, "DATE")]),
    ("show expenses last month", [(14, 24, "DATE")]),
    ("spending this month", [(9, 19, "DATE")]),
    ("transactions in january", [(16, 23, "DATE")]),
    ("february expenses", [(0, 8, "DATE")]),
    ("last week spending", [(0, 9, "DATE")]),
    ("expenses this week", [(9, 18, "DATE")]),
    ("transactions from march 5", [(18, 25, "DATE")]),
    ("spending on monday", [(12, 18, "DATE")]),
    ("purchases 3 days ago", [(10, 20, "DATE")]),
    ("transactions last friday", [(13, 24, "DATE")]),
    ("this year expenses", [(0, 9, "DATE")]),
    ("last year spending", [(0, 9, "DATE")]),
    ("december 31 transactions", [(0, 11, "DATE")]),

    # amount entities
    ("transactions above 500", [(13, 22, "AMOUNT")]),
    ("spending below 100", [(9, 18, "AMOUNT")]),
    ("purchases over 1000", [(10, 19, "AMOUNT")]),
    ("expenses more than 2000", [(9, 23, "AMOUNT")]),
    ("transactions under 50", [(13, 21, "AMOUNT")]),
    ("orders above 300 rupees", [(7, 23, "AMOUNT")]),
    ("less than 200 spent", [(0, 13, "AMOUNT")]),
    ("greater than 5000", [(0, 17, "AMOUNT")]),

    # combined entities
    ("how many swiggy transactions last month", [(9, 15, "MERCHANT"), (29, 39, "DATE")]),
    ("total spent on zomato this month", [(15, 21, "MERCHANT"), (22, 32, "DATE")]),
    ("amazon orders above 500", [(0, 6, "MERCHANT"), (14, 23, "AMOUNT")]),
    ("food expenses last month", [(0, 4, "CATEGORY"), (14, 24, "DATE")]),
    ("show uber rides yesterday", [(5, 9, "MERCHANT"), (16, 25, "DATE")]),
    ("grocery spending this week", [(0, 7, "CATEGORY"), (17, 26, "DATE")]),
    ("shopping transactions above 1000 last month", [(0, 8, "CATEGORY"), (22, 32, "AMOUNT"), (33, 43, "DATE")]),
    ("netflix payments this year", [(0, 7, "MERCHANT"), (17, 26, "DATE")]),
    ("swiggy orders above 200 this month", [(0, 6, "MERCHANT"), (14, 23, "AMOUNT"), (24, 34, "DATE")]),
    ("food and dining expenses in february", [(0, 15, "CATEGORY"), (28, 36, "DATE")]),

    # card entities (single)
    ("sbi card transactions", [(0, 3, "CARD")]),
    ("hdfc card expenses", [(0, 4, "CARD")]),
    ("icici card spending", [(0, 5, "CARD")]),
    ("show axis card transactions", [(5, 9, "CARD")]),
    ("kotak card payments", [(0, 5, "CARD")]),
    ("transactions on my hdfc card", [(19, 23, "CARD")]),
    ("how many citi card orders", [(9, 13, "CARD")]),
    ("amex card expenses", [(0, 4, "CARD")]),
    ("total spent on rbl card", [(15, 18, "CARD")]),
    ("indusind card transactions", [(0, 8, "CARD")]),
    ("yes bank card spending", [(0, 8, "CARD")]),
    ("bob card transactions", [(0, 3, "CARD")]),
    ("chase card expenses", [(0, 5, "CARD")]),
    ("bofa card spending", [(0, 4, "CARD")]),
    ("capital one card transactions", [(0, 11, "CARD")]),

    # card + date combined
    ("sbi card transactions last month", [(0, 3, "CARD"), (22, 32, "DATE")]),
    ("hdfc card expenses this month", [(0, 4, "CARD"), (19, 29, "DATE")]),
    ("icici card spending yesterday", [(0, 5, "CARD"), (20, 29, "DATE")]),
    ("show axis card transactions this week", [(5, 9, "CARD"), (26, 35, "DATE")]),
    ("kotak card orders in january", [(0, 5, "CARD"), (21, 28, "DATE")]),

    # card + merchant combined
    ("swiggy transactions on sbi card", [(0, 6, "MERCHANT"), (23, 26, "CARD")]),
    ("hdfc card amazon orders", [(0, 4, "CARD"), (10, 16, "MERCHANT")]),
    ("zomato orders on icici card", [(0, 6, "MERCHANT"), (17, 22, "CARD")]),
    ("my swiggy transactions in sbi card", [(3, 9, "MERCHANT"), (26, 29, "CARD")]),
    ("uber rides on hdfc card", [(0, 4, "MERCHANT"), (14, 18, "CARD")]),
    ("show netflix payments on icici card", [(5, 12, "MERCHANT"), (25, 30, "CARD")]),
    ("amazon orders from my axis card", [(0, 6, "MERCHANT"), (22, 26, "CARD")]),
    ("flipkart transactions in kotak card", [(0, 8, "MERCHANT"), (25, 30, "CARD")]),
    ("how much on swiggy in sbi card", [(12, 18, "MERCHANT"), (22, 25, "CARD")]),
    ("total spent on zomato on hdfc card", [(15, 21, "MERCHANT"), (25, 29, "CARD")]),
    ("starbucks on my icici card", [(0, 9, "MERCHANT"), (16, 21, "CARD")]),
    ("sbi card swiggy transactions", [(0, 3, "CARD"), (9, 15, "MERCHANT")]),
    ("icici card uber expenses", [(0, 5, "CARD"), (11, 15, "MERCHANT")]),
    ("my netflix on axis card", [(3, 10, "MERCHANT"), (14, 18, "CARD")]),

    # card + category combined
    ("hdfc card food expenses", [(0, 4, "CARD"), (10, 14, "CATEGORY")]),
    ("sbi card shopping spending", [(0, 3, "CARD"), (9, 17, "CATEGORY")]),
    ("icici card grocery purchases", [(0, 5, "CARD"), (11, 18, "CATEGORY")]),
    ("food transactions on sbi card", [(0, 4, "CATEGORY"), (21, 24, "CARD")]),
    ("shopping expenses on hdfc card", [(0, 8, "CATEGORY"), (21, 25, "CARD")]),
    ("entertainment on my icici card", [(0, 13, "CATEGORY"), (20, 25, "CARD")]),
    ("travel spending on axis card", [(0, 6, "CATEGORY"), (19, 23, "CARD")]),
    ("grocery purchases on kotak card", [(0, 7, "CATEGORY"), (21, 26, "CARD")]),

    # card + amount combined
    ("sbi card transactions above 500", [(0, 3, "CARD"), (22, 31, "AMOUNT")]),
    ("hdfc card expenses over 1000", [(0, 4, "CARD"), (19, 28, "AMOUNT")]),
    ("icici card transactions above 1000", [(0, 5, "CARD"), (24, 34, "AMOUNT")]),
    ("transactions under 200 on axis card", [(13, 22, "AMOUNT"), (26, 30, "CARD")]),
    ("kotak card expenses over 500", [(0, 5, "CARD"), (20, 28, "AMOUNT")]),
    ("spending below 100 on sbi card", [(9, 18, "AMOUNT"), (22, 25, "CARD")]),

    # triple combos: card + category + date
    ("hdfc card food expenses this month", [(0, 4, "CARD"), (10, 14, "CATEGORY"), (24, 34, "DATE")]),
    ("sbi card shopping last month", [(0, 3, "CARD"), (9, 17, "CATEGORY"), (18, 28, "DATE")]),
    ("food spending on sbi card this month", [(0, 4, "CATEGORY"), (17, 20, "CARD"), (26, 36, "DATE")]),
    ("shopping on hdfc card last week", [(0, 8, "CATEGORY"), (12, 16, "CARD"), (22, 31, "DATE")]),
    ("entertainment on icici card last month", [(0, 13, "CATEGORY"), (17, 22, "CARD"), (28, 38, "DATE")]),
    ("grocery purchases on axis card in january", [(0, 7, "CATEGORY"), (21, 25, "CARD"), (34, 41, "DATE")]),

    # triple: merchant + card + date (card before date)
    ("swiggy on sbi card last month", [(0, 6, "MERCHANT"), (10, 13, "CARD"), (19, 29, "DATE")]),
    ("my zomato orders in hdfc card this month", [(3, 9, "MERCHANT"), (20, 24, "CARD"), (30, 40, "DATE")]),
    ("amazon on icici card last week", [(0, 6, "MERCHANT"), (10, 15, "CARD"), (21, 30, "DATE")]),
    ("uber rides on axis card yesterday", [(0, 4, "MERCHANT"), (14, 18, "CARD"), (24, 33, "DATE")]),

    # triple: merchant + date + card (date before card)
    ("my swiggy transactions in january with sbi card", [(3, 9, "MERCHANT"), (26, 33, "DATE"), (39, 42, "CARD")]),
    ("zomato orders in february on hdfc card", [(0, 6, "MERCHANT"), (17, 25, "DATE"), (29, 33, "CARD")]),
    ("amazon purchases last month from icici card", [(0, 6, "MERCHANT"), (17, 27, "DATE"), (33, 38, "CARD")]),
    ("uber rides this week on sbi card", [(0, 4, "MERCHANT"), (11, 20, "DATE"), (24, 27, "CARD")]),
    ("netflix payments in march with axis card", [(0, 7, "MERCHANT"), (20, 25, "DATE"), (31, 35, "CARD")]),
    ("swiggy orders last week from hdfc card", [(0, 6, "MERCHANT"), (14, 23, "DATE"), (29, 33, "CARD")]),
    ("flipkart purchases in january on kotak card", [(0, 8, "MERCHANT"), (22, 29, "DATE"), (33, 38, "CARD")]),
    ("starbucks this month with icici card", [(0, 9, "MERCHANT"), (10, 20, "DATE"), (26, 31, "CARD")]),
    ("how much on swiggy in january from sbi card", [(12, 18, "MERCHANT"), (22, 29, "DATE"), (35, 38, "CARD")]),
    ("total zomato in february with hdfc card", [(6, 12, "MERCHANT"), (16, 24, "DATE"), (30, 34, "CARD")]),

    # triple: card + date + merchant
    ("sbi card january swiggy orders", [(0, 3, "CARD"), (9, 16, "DATE"), (17, 23, "MERCHANT")]),
    ("hdfc card last month amazon spending", [(0, 4, "CARD"), (10, 20, "DATE"), (21, 27, "MERCHANT")]),

    # quad: merchant + date + card + category/amount
    ("swiggy food in january with sbi card", [(0, 6, "MERCHANT"), (7, 11, "CATEGORY"), (15, 22, "DATE"), (28, 31, "CARD")]),
    ("amazon orders above 500 last month on hdfc card", [(0, 6, "MERCHANT"), (14, 23, "AMOUNT"), (24, 34, "DATE"), (38, 42, "CARD")]),

    # triple: card + category + amount
    ("food expenses above 500 on sbi card", [(0, 4, "CATEGORY"), (14, 23, "AMOUNT"), (27, 30, "CARD")]),
    ("shopping transactions over 1000 on hdfc card", [(0, 8, "CATEGORY"), (22, 31, "AMOUNT"), (35, 39, "CARD")]),
    ("grocery purchases under 200 on icici card", [(0, 7, "CATEGORY"), (18, 27, "AMOUNT"), (31, 36, "CARD")]),

    # triple: merchant + amount + card
    ("swiggy orders above 200 on sbi card", [(0, 6, "MERCHANT"), (14, 23, "AMOUNT"), (27, 30, "CARD")]),
    ("amazon purchases over 1000 from hdfc card", [(0, 6, "MERCHANT"), (17, 26, "AMOUNT"), (32, 36, "CARD")]),
    ("uber rides above 300 on icici card", [(0, 4, "MERCHANT"), (11, 20, "AMOUNT"), (24, 29, "CARD")]),

    # quad: merchant + category + date + card
    ("zomato food orders in february with hdfc card", [(0, 6, "MERCHANT"), (7, 11, "CATEGORY"), (22, 30, "DATE"), (36, 40, "CARD")]),
    ("amazon shopping last month on icici card", [(0, 6, "MERCHANT"), (7, 15, "CATEGORY"), (16, 26, "DATE"), (30, 35, "CARD")]),

    # quad: merchant + amount + date + card
    ("swiggy orders above 500 last month on sbi card", [(0, 6, "MERCHANT"), (14, 23, "AMOUNT"), (24, 34, "DATE"), (38, 41, "CARD")]),
    ("uber rides over 200 this week from hdfc card", [(0, 4, "MERCHANT"), (11, 19, "AMOUNT"), (20, 29, "DATE"), (35, 39, "CARD")]),

    # === Entity annotations derived from intent examples ===

    # -- count_transactions --
    ("how many times did I order from zomato", [(32, 38, "MERCHANT")]),
    ("number of uber rides", [(10, 14, "MERCHANT")]),
    ("how many payments to netflix", [(21, 28, "MERCHANT")]),
    ("how many food transactions", [(9, 13, "CATEGORY")]),
    ("how many shopping transactions this month", [(9, 17, "CATEGORY"), (31, 41, "DATE")]),
    ("count my grocery purchases", [(9, 16, "CATEGORY")]),
    ("number of swiggy orders last month", [(10, 16, "MERCHANT"), (24, 34, "DATE")]),
    ("how many flipkart orders", [(9, 17, "MERCHANT")]),
    ("count my entertainment expenses", [(9, 22, "CATEGORY")]),
    ("how many fuel payments", [(9, 13, "CATEGORY")]),
    ("how many ola rides this week", [(9, 12, "MERCHANT"), (19, 28, "DATE")]),
    ("how many transactions in january", [(25, 32, "DATE")]),
    ("count transactions above 500", [(19, 28, "AMOUNT")]),
    ("how many transactions below 100", [(22, 31, "AMOUNT")]),
    ("how many transactions on my hdfc card", [(28, 32, "CARD")]),
    ("how many times I ordered from starbucks", [(30, 39, "MERCHANT")]),
    ("number of dining transactions", [(10, 16, "CATEGORY")]),
    ("how many transfers did I make", [(9, 18, "CATEGORY")]),
    ("number of medical expenses", [(10, 17, "CATEGORY")]),
    ("how many travel bookings", [(9, 15, "CATEGORY")]),
    ("how many sbi card transactions", [(9, 12, "CARD")]),
    ("count icici card orders", [(6, 11, "CARD")]),
    ("how many transactions on my axis card", [(28, 32, "CARD")]),
    ("how many swiggy orders on sbi card", [(9, 15, "MERCHANT"), (26, 29, "CARD")]),
    ("count amazon transactions in hdfc card", [(6, 12, "MERCHANT"), (29, 33, "CARD")]),
    ("how many swiggy orders in january on sbi card", [(9, 15, "MERCHANT"), (26, 33, "DATE"), (37, 40, "CARD")]),
    ("count uber rides last month with hdfc card", [(6, 10, "MERCHANT"), (17, 27, "DATE"), (33, 37, "CARD")]),
    ("how many sbi card transactions last month", [(9, 12, "CARD"), (31, 41, "DATE")]),
    ("count hdfc card transactions this week", [(6, 10, "CARD"), (29, 38, "DATE")]),
    ("how many food transactions on sbi card", [(9, 13, "CATEGORY"), (30, 33, "CARD")]),
    ("count transactions above 500 on hdfc card", [(19, 28, "AMOUNT"), (32, 36, "CARD")]),
    ("how many grocery transactions on icici card this month", [(9, 16, "CATEGORY"), (33, 38, "CARD"), (44, 54, "DATE")]),
    ("how many swiggy orders above 200 on sbi card", [(9, 15, "MERCHANT"), (23, 32, "AMOUNT"), (36, 39, "CARD")]),
    # -- total_spent --
    ("how much did I spend on swiggy", [(24, 30, "MERCHANT")]),
    ("total spent on food", [(15, 19, "CATEGORY")]),
    ("how much money spent on shopping", [(24, 32, "CATEGORY")]),
    ("how much spent on zomato this month", [(18, 24, "MERCHANT"), (25, 35, "DATE")]),
    ("total amount spent on groceries", [(22, 31, "CATEGORY")]),
    ("how much did I spend on uber", [(24, 28, "MERCHANT")]),
    ("how much on entertainment", [(12, 25, "CATEGORY")]),
    ("total transportation cost", [(6, 20, "CATEGORY")]),
    ("how much did I spend last month", [(21, 31, "DATE")]),
    ("how much money did I spend on travel", [(30, 36, "CATEGORY")]),
    ("total spent on amazon", [(15, 21, "MERCHANT")]),
    ("how much on bills and utilities", [(12, 17, "CATEGORY"), (22, 31, "CATEGORY")]),
    ("total education expenses", [(6, 15, "CATEGORY")]),
    ("what did I spend on health", [(20, 26, "CATEGORY")]),
    ("how much spent on netflix subscription", [(18, 25, "MERCHANT")]),
    ("total shopping spend this month", [(6, 14, "CATEGORY"), (21, 31, "DATE")]),
    ("total debits this month", [(13, 23, "DATE")]),
    ("how much did I spend on fuel", [(24, 28, "CATEGORY")]),
    ("total restaurant expenses", [(6, 16, "CATEGORY")]),
    ("total amount on flipkart", [(16, 24, "MERCHANT")]),
    ("sum of grocery purchases", [(7, 14, "CATEGORY")]),
    ("total spending on my sbi card", [(21, 24, "CARD")]),
    ("how much did I spend on hdfc card", [(24, 28, "CARD")]),
    ("total spent on icici credit card", [(15, 20, "CARD")]),
    ("how much on my axis card", [(15, 19, "CARD")]),
    ("total zomato spending on hdfc card", [(6, 12, "MERCHANT"), (25, 29, "CARD")]),
    ("how much on swiggy in january with sbi card", [(12, 18, "MERCHANT"), (22, 29, "DATE"), (35, 38, "CARD")]),
    ("total zomato spending last month from hdfc card", [(6, 12, "MERCHANT"), (22, 32, "DATE"), (38, 42, "CARD")]),
    ("total spent on sbi card last month", [(15, 18, "CARD"), (24, 34, "DATE")]),
    ("how much on hdfc card this week", [(12, 16, "CARD"), (22, 31, "DATE")]),
    ("total food spending on icici card", [(6, 10, "CATEGORY"), (23, 28, "CARD")]),
    ("total spent above 1000 on sbi card", [(12, 22, "AMOUNT"), (26, 29, "CARD")]),
    ("total food expenses on hdfc card this month", [(6, 10, "CATEGORY"), (23, 27, "CARD"), (33, 43, "DATE")]),
    ("how much on swiggy above 500 from sbi card", [(12, 18, "MERCHANT"), (19, 28, "AMOUNT"), (34, 37, "CARD")]),
    # -- transactions_on_date --
    ("what did I spend yesterday", [(17, 26, "DATE")]),
    ("show transactions from today", [(23, 28, "DATE")]),
    ("what did I buy today", [(15, 20, "DATE")]),
    ("transactions on march 5", [(16, 23, "DATE")]),
    ("show me yesterday's expenses", [(8, 17, "DATE")]),
    ("what happened on february 14", [(17, 25, "DATE")]),
    ("list transactions from last friday", [(23, 34, "DATE")]),
    ("show my spending for today", [(21, 26, "DATE")]),
    ("what purchases did I make on 1st march", [(29, 38, "DATE")]),
    ("transactions from the 15th", [(18, 26, "DATE")]),
    ("what did I buy on january 26", [(18, 28, "DATE")]),
    ("spending on christmas day", [(12, 25, "DATE")]),
    ("show me december 31 transactions", [(8, 19, "DATE")]),
    ("what did I spend 3 days ago", [(17, 27, "DATE")]),
    ("transactions from last saturday", [(18, 31, "DATE")]),
    ("show purchases from feb 28", [(20, 26, "DATE")]),
    ("what did I buy this morning", [(15, 27, "DATE")]),
    ("expenses on diwali", [(12, 18, "DATE")]),
    ("transactions for march 1st", [(17, 26, "DATE")]),
    ("sbi card transactions yesterday", [(0, 3, "CARD"), (22, 31, "DATE")]),
    ("what did I spend on hdfc card today", [(20, 24, "CARD"), (30, 35, "DATE")]),
    ("swiggy orders yesterday on sbi card", [(0, 6, "MERCHANT"), (14, 23, "DATE"), (27, 30, "CARD")]),
    ("show uber transactions today on hdfc card", [(5, 9, "MERCHANT"), (23, 28, "DATE"), (32, 36, "CARD")]),
    ("food transactions yesterday on icici card", [(0, 4, "CATEGORY"), (18, 27, "DATE"), (31, 36, "CARD")]),
    ("shopping expenses today on axis card", [(0, 8, "CATEGORY"), (18, 23, "DATE"), (27, 31, "CARD")]),
    ("transactions above 500 yesterday on sbi card", [(13, 22, "AMOUNT"), (23, 32, "DATE"), (36, 39, "CARD")]),
    ("what were my spends on 10th february", [(23, 36, "DATE")]),
    ("anything charged on tuesday last week", [(28, 37, "DATE")]),
    ("did I pay for anything on jan 2", [(26, 31, "DATE")]),
    ("show me what I bought two days ago", [(22, 34, "DATE")]),
    ("amazon purchases on march 12 on hdfc card", [(0, 6, "MERCHANT"), (20, 28, "DATE"), (32, 36, "CARD")]),
    ("how much did I spend last wednesday", [(21, 35, "DATE")]),
    ("any transactions on new year's eve", [(20, 34, "DATE")]),
    ("grocery expenses from last sunday on icici card", [(0, 7, "CATEGORY"), (22, 33, "DATE"), (37, 42, "CARD")]),
    ("payments made on the 20th of january", [(17, 36, "DATE")]),
    ("what went out on 5th jan on axis card", [(17, 24, "DATE"), (28, 32, "CARD")]),
    ("zomato orders from last thursday", [(0, 6, "MERCHANT"), (19, 32, "DATE")]),
    ("show all debits on feb 14 on sbi card", [(19, 25, "DATE"), (29, 32, "CARD")]),
    ("did anything get charged the day before yesterday", [(25, 49, "DATE")]),
    # -- category_spend --
    ("how much did I spend on food and dining", [(24, 39, "CATEGORY")]),
    ("show my grocery spending", [(8, 15, "CATEGORY")]),
    ("what is my shopping expense", [(11, 19, "CATEGORY")]),
    ("transportation costs breakdown", [(0, 14, "CATEGORY")]),
    ("health and medical expenses", [(0, 18, "CATEGORY")]),
    ("travel expenses this month", [(0, 6, "CATEGORY"), (16, 26, "DATE")]),
    ("education costs", [(0, 9, "CATEGORY")]),
    ("finance and investment outflow", [(0, 22, "CATEGORY")]),
    ("transfer amounts", [(0, 8, "CATEGORY")]),
    ("break down my food spending", [(14, 18, "CATEGORY")]),
    ("food vs shopping comparison", [(0, 4, "CATEGORY"), (8, 16, "CATEGORY")]),
    ("what percentage is food", [(19, 23, "CATEGORY")]),
    ("dining expenses this month", [(0, 6, "CATEGORY"), (16, 26, "DATE")]),
    ("hdfc card food spending", [(0, 4, "CARD"), (10, 14, "CATEGORY")]),
    ("sbi card shopping expenses", [(0, 3, "CARD"), (9, 17, "CATEGORY")]),
    ("category breakdown for sbi card", [(23, 26, "CARD")]),
    ("food spending on hdfc card this month", [(0, 4, "CATEGORY"), (17, 21, "CARD"), (27, 37, "DATE")]),
    ("shopping expenses on icici card last month", [(0, 8, "CATEGORY"), (21, 26, "CARD"), (32, 42, "DATE")]),
    ("swiggy food spending on hdfc card", [(0, 6, "MERCHANT"), (7, 11, "CATEGORY"), (24, 28, "CARD")]),
    ("how much went to utilities and bills last month", [(17, 36, "CATEGORY"), (37, 47, "DATE")]),
    ("what did I spend on education this year on axis card", [(20, 29, "CATEGORY"), (30, 39, "DATE"), (43, 47, "CARD")]),
    ("show me my travel spending compared to last month", [(11, 17, "CATEGORY"), (39, 49, "DATE")]),
    ("what percentage of my spending is entertainment", [(34, 47, "CATEGORY")]),
    ("break down transportation vs travel expenses", [(11, 25, "CATEGORY"), (29, 35, "CATEGORY")]),
    ("any health and medical bills on icici card this month", [(4, 22, "CATEGORY"), (32, 37, "CARD"), (43, 53, "DATE")]),
    ("how much am I spending on groceries each month", [(26, 35, "CATEGORY")]),
    ("other category expenses on hdfc card last month", [(0, 5, "CATEGORY"), (27, 31, "CARD"), (37, 47, "DATE")]),
    ("education fees on sbi card above 10000", [(0, 9, "CATEGORY"), (18, 21, "CARD"), (27, 38, "AMOUNT")]),
    ("total transfers on axis card this month", [(6, 15, "CATEGORY"), (19, 23, "CARD"), (29, 39, "DATE")]),
    ("what did I blow on entertainment last weekend", [(19, 32, "CATEGORY"), (33, 45, "DATE")]),
    # -- list_transactions --
    ("show me all swiggy orders", [(12, 18, "MERCHANT")]),
    ("list zomato transactions", [(5, 11, "MERCHANT")]),
    ("show shopping transactions", [(5, 13, "CATEGORY")]),
    ("list food expenses", [(5, 9, "CATEGORY")]),
    ("show transactions above 1000", [(18, 28, "AMOUNT")]),
    ("list transactions below 200", [(18, 27, "AMOUNT")]),
    ("list all orders from amazon", [(21, 27, "MERCHANT")]),
    ("show sbi card transactions", [(5, 8, "CARD")]),
    ("list hdfc card expenses", [(5, 9, "CARD")]),
    ("show transactions on my kotak card", [(24, 29, "CARD")]),
    ("show uber rides on hdfc card", [(5, 9, "MERCHANT"), (19, 23, "CARD")]),
    ("amazon orders from my icici card", [(0, 6, "MERCHANT"), (22, 27, "CARD")]),
    ("show amazon orders last month from hdfc card", [(5, 11, "MERCHANT"), (19, 29, "DATE"), (35, 39, "CARD")]),
    ("show sbi card transactions this month", [(5, 8, "CARD"), (27, 37, "DATE")]),
    ("list hdfc card expenses last week", [(5, 9, "CARD"), (24, 33, "DATE")]),
    ("show food transactions on icici card", [(5, 9, "CATEGORY"), (26, 31, "CARD")]),
    ("list sbi card transactions above 1000", [(5, 8, "CARD"), (27, 37, "AMOUNT")]),
    ("show shopping transactions on hdfc card this month", [(5, 13, "CATEGORY"), (30, 34, "CARD"), (40, 50, "DATE")]),
    ("pull up my netflix transactions", [(11, 18, "MERCHANT")]),
    ("get me all flipkart orders from last month", [(11, 19, "MERCHANT"), (32, 42, "DATE")]),
    ("what do I have from blinkit this week", [(20, 27, "MERCHANT"), (28, 37, "DATE")]),
    ("show ola rides above 500", [(5, 8, "MERCHANT"), (15, 24, "AMOUNT")]),
    ("any transactions between 200 and 1000", [(17, 37, "AMOUNT")]),
    ("lemme see my entertainment expenses on kotak card", [(13, 26, "CATEGORY"), (39, 44, "CARD")]),
    ("list all blinkit and swiggy transactions in february", [(9, 16, "MERCHANT"), (21, 27, "MERCHANT"), (44, 52, "DATE")]),
    # -- highest_transaction --
    ("biggest food expense", [(8, 12, "CATEGORY")]),
    ("highest shopping purchase", [(8, 16, "CATEGORY")]),
    ("what was my highest spend this month", [(26, 36, "DATE")]),
    ("biggest transaction last month", [(20, 30, "DATE")]),
    ("biggest expense on hdfc card", [(19, 23, "CARD")]),
    ("largest sbi card transaction", [(8, 11, "CARD")]),
    ("biggest swiggy order on sbi card", [(8, 14, "MERCHANT"), (24, 27, "CARD")]),
    ("biggest swiggy order in january with hdfc card", [(8, 14, "MERCHANT"), (24, 31, "DATE"), (37, 41, "CARD")]),
    ("biggest sbi card expense last month", [(8, 11, "CARD"), (25, 35, "DATE")]),
    ("highest food expense on hdfc card", [(8, 12, "CATEGORY"), (24, 28, "CARD")]),
    ("most expensive swiggy order on sbi card", [(15, 21, "MERCHANT"), (31, 34, "CARD")]),
    ("biggest shopping expense on icici card this month", [(8, 16, "CATEGORY"), (28, 33, "CARD"), (39, 49, "DATE")]),
    ("costliest purchase this month", [(19, 29, "DATE")]),
    ("priciest order on zomato", [(18, 24, "MERCHANT")]),
    ("what was the peak spending last week", [(27, 36, "DATE")]),
    ("top expense on amazon this month", [(15, 21, "MERCHANT"), (22, 32, "DATE")]),
    ("which transaction was the largest on my hdfc card in february", [(40, 44, "CARD"), (53, 61, "DATE")]),
    ("max grocery expense on sbi card", [(4, 11, "CATEGORY"), (23, 26, "CARD")]),
    ("my most expensive uber ride", [(18, 22, "MERCHANT")]),
    ("biggest flipkart order this year", [(8, 16, "MERCHANT"), (23, 32, "DATE")]),
    ("what did I spend the most on last month", [(29, 39, "DATE")]),
    ("highest netflix payment on icici card", [(8, 15, "MERCHANT"), (27, 32, "CARD")]),
    ("show me the costliest dining expense", [(22, 28, "CATEGORY")]),
    ("largest entertainment spend this month", [(8, 21, "CATEGORY"), (28, 38, "DATE")]),
    ("priciest travel expense on hdfc card last month", [(9, 15, "CATEGORY"), (27, 31, "CARD"), (37, 47, "DATE")]),
    ("which was the most I ever paid on zomato with sbi card", [(34, 40, "MERCHANT"), (46, 49, "CARD")]),
    ("whats my biggest grocery bill", [(17, 24, "CATEGORY")]),
    ("top spending on amazon in march with icici card", [(16, 22, "MERCHANT"), (26, 31, "DATE"), (37, 42, "CARD")]),
    # -- lowest_transaction --
    ("smallest transaction on sbi card", [(24, 27, "CARD")]),
    ("smallest sbi card transaction last month", [(9, 12, "CARD"), (30, 40, "DATE")]),
    ("cheapest uber ride on hdfc card", [(9, 13, "MERCHANT"), (22, 26, "CARD")]),
    ("lowest food expense on icici card", [(7, 11, "CATEGORY"), (23, 28, "CARD")]),
    ("smallest swiggy order on sbi card this month", [(9, 15, "MERCHANT"), (25, 28, "CARD"), (34, 44, "DATE")]),
    ("cheapest grocery purchase on hdfc card last month", [(9, 16, "CATEGORY"), (29, 33, "CARD"), (39, 49, "DATE")]),
    ("lowest transaction under 100 on axis card", [(19, 28, "AMOUNT"), (32, 36, "CARD")]),
    ("cheapest zomato order under 200 on sbi card", [(9, 15, "MERCHANT"), (22, 31, "AMOUNT"), (35, 38, "CARD")]),
    ("what was the tiniest purchase on my kotak card", [(36, 41, "CARD")]),
    ("most affordable transaction last week", [(28, 37, "DATE")]),
    ("show me my least expensive order on amex card", [(36, 40, "CARD")]),
    ("smallest amazon purchase this month", [(9, 15, "MERCHANT"), (25, 35, "DATE")]),
    ("what's the lowest amount I paid on hdfc card last month", [(35, 39, "CARD"), (45, 55, "DATE")]),
    ("cheapest netflix charge on icici card", [(9, 16, "MERCHANT"), (27, 32, "CARD")]),
    ("minimum transaction on axis card in january", [(23, 27, "CARD"), (36, 43, "DATE")]),
    ("tiniest expense on sbi card yesterday", [(19, 22, "CARD"), (28, 37, "DATE")]),
    ("least expensive grocery order on kotak card", [(16, 23, "CATEGORY"), (33, 38, "CARD")]),
    ("lowest ola ride fare on hdfc card this month", [(7, 10, "MERCHANT"), (24, 28, "CARD"), (34, 44, "DATE")]),
    ("smallest blinkit order on sbi card", [(9, 16, "MERCHANT"), (26, 29, "CARD")]),
    ("what was my cheapest starbucks purchase", [(21, 30, "MERCHANT")]),
    ("most affordable shopping transaction on amex card last month", [(16, 24, "CATEGORY"), (40, 44, "CARD"), (50, 60, "DATE")]),
    ("lowest entertainment expense on icici card", [(7, 20, "CATEGORY"), (32, 37, "CARD")]),
    ("smallest health related transaction under 500", [(9, 15, "CATEGORY"), (36, 45, "AMOUNT")]),
    ("cheapest flipkart order on axis card this month", [(9, 17, "MERCHANT"), (27, 31, "CARD"), (37, 47, "DATE")]),
    ("minimum amount paid on kotak card last week", [(23, 28, "CARD"), (34, 43, "DATE")]),
    ("what's the least I spent on transportation", [(28, 42, "CATEGORY")]),
    ("tiniest food expense on hdfc card in february", [(8, 12, "CATEGORY"), (24, 28, "CARD"), (37, 45, "DATE")]),
    ("show me the smallest transaction under 50", [(33, 41, "AMOUNT")]),
    ("lowest spending on my sbi card this week", [(22, 25, "CARD"), (31, 40, "DATE")]),
    ("cheapest purchase I made yesterday on icici card", [(25, 34, "DATE"), (38, 43, "CARD")]),
    # -- average_spend --
    ("average food expense", [(8, 12, "CATEGORY")]),
    ("average grocery bill", [(8, 15, "CATEGORY")]),
    ("average shopping expense", [(8, 16, "CATEGORY")]),
    ("average uber ride cost", [(8, 12, "MERCHANT")]),
    ("average spending on swiggy", [(20, 26, "MERCHANT")]),
    ("average spend on hdfc card", [(17, 21, "CARD")]),
    ("average icici card transaction", [(8, 13, "CARD")]),
    ("average swiggy order on sbi card", [(8, 14, "MERCHANT"), (24, 27, "CARD")]),
    ("average spending on sbi card last month", [(20, 23, "CARD"), (29, 39, "DATE")]),
    ("average food expense on hdfc card", [(8, 12, "CATEGORY"), (24, 28, "CARD")]),
    ("average swiggy spend on icici card this month", [(8, 14, "MERCHANT"), (24, 29, "CARD"), (35, 45, "DATE")]),
    ("average grocery spending on axis card last month", [(8, 15, "CATEGORY"), (28, 32, "CARD"), (38, 48, "DATE")]),
    ("average uber ride above 100 on sbi card", [(8, 12, "MERCHANT"), (18, 27, "AMOUNT"), (31, 34, "CARD")]),
    ("how much do I normally spend on zomato", [(32, 38, "MERCHANT")]),
    ("what's my usual amazon order amount", [(16, 22, "MERCHANT")]),
    ("typical flipkart purchase amount", [(8, 16, "MERCHANT")]),
    ("mean netflix charge per month", [(5, 12, "MERCHANT")]),
    ("average blinkit order cost", [(8, 15, "MERCHANT")]),
    ("what's the normal spend on entertainment", [(27, 40, "CATEGORY")]),
    ("average travel expense this month", [(8, 14, "CATEGORY"), (23, 33, "DATE")]),
    ("how much do I usually spend on dining", [(31, 37, "CATEGORY")]),
    ("average health spending on kotak card", [(8, 14, "CATEGORY"), (27, 32, "CARD")]),
    ("typical education expense on amex card", [(8, 17, "CATEGORY"), (29, 33, "CARD")]),
    ("per-transaction average on rbl card", [(27, 30, "CARD")]),
    ("usual utility bill amount last month", [(26, 36, "DATE")]),
    ("average ola ride cost this week", [(8, 11, "MERCHANT"), (22, 31, "DATE")]),
    ("what do I typically spend at starbucks", [(29, 38, "MERCHANT")]),
    ("mean spending on groceries in february", [(17, 26, "CATEGORY"), (30, 38, "DATE")]),
    ("average entertainment expense on axis card last week", [(8, 21, "CATEGORY"), (33, 37, "CARD"), (43, 52, "DATE")]),
    ("how much is my normal monthly spend on food", [(39, 43, "CATEGORY")]),
    # -- monthly_summary --
    ("how was my spending this month", [(20, 30, "DATE")]),
    ("this month overview", [(0, 10, "DATE")]),
    ("show me this month's report", [(8, 18, "DATE")]),
    ("how did I spend in february", [(19, 27, "DATE")]),
    ("january spending summary", [(0, 7, "DATE")]),
    ("this month's expenses summary", [(0, 10, "DATE")]),
    ("spending overview for march", [(22, 27, "DATE")]),
    ("last month summary", [(0, 10, "DATE")]),
    ("compare this month vs last month", [(8, 18, "DATE"), (22, 32, "DATE")]),
    ("monthly summary for sbi card", [(20, 23, "CARD")]),
    ("hdfc card monthly spending", [(0, 4, "CARD")]),
    ("sbi card swiggy monthly summary", [(0, 3, "CARD"), (9, 15, "MERCHANT")]),
    ("hdfc card food spending monthly", [(0, 4, "CARD"), (10, 14, "CATEGORY")]),
    ("monthly swiggy spending on sbi card in january", [(8, 14, "MERCHANT"), (27, 30, "CARD"), (39, 46, "DATE")]),
    ("monthly food spending on hdfc card last month", [(8, 12, "CATEGORY"), (25, 29, "CARD"), (35, 45, "DATE")]),
    ("give me a recap of april spending", [(19, 24, "DATE")]),
    ("spending snapshot for may", [(22, 25, "DATE")]),
    ("how am I doing this month financially", [(15, 25, "DATE")]),
    ("review my june expenses", [(10, 14, "DATE")]),
    ("show me a breakdown of july spending", [(23, 27, "DATE")]),
    ("august expense analysis", [(0, 6, "DATE")]),
    ("september spending overview on icici card", [(0, 9, "DATE"), (31, 36, "CARD")]),
    ("axis card monthly recap", [(0, 4, "CARD")]),
    ("kotak card spending summary for october", [(0, 5, "CARD"), (32, 39, "DATE")]),
    ("amex card monthly expense overview", [(0, 4, "CARD")]),
    ("how does this month compare to previous months", [(9, 19, "DATE")]),
    ("spending trend over the last few months", [(24, 39, "DATE")]),
    ("november grocery spending summary", [(0, 8, "DATE"), (9, 16, "CATEGORY")]),
    ("december shopping expenses breakdown", [(0, 8, "DATE"), (9, 17, "CATEGORY")]),
    ("monthly entertainment spending report", [(8, 21, "CATEGORY")]),
    ("travel expenses this month on axis card", [(0, 6, "CATEGORY"), (16, 26, "DATE"), (30, 34, "CARD")]),
    ("amazon spending recap for november on kotak card", [(0, 6, "MERCHANT"), (26, 34, "DATE"), (38, 43, "CARD")]),
    ("zomato monthly summary on amex card", [(0, 6, "MERCHANT"), (26, 30, "CARD")]),

    # -- compare_months --
    ("compare january and february spending", [(8, 15, "DATE"), (20, 28, "DATE")]),
    ("how does february compare to january", [(9, 17, "DATE"), (29, 36, "DATE")]),
    ("march vs april spending", [(0, 5, "DATE"), (9, 14, "DATE")]),
    ("compare food spending this month vs last", [(8, 12, "CATEGORY"), (22, 32, "DATE")]),
    ("how does grocery spending compare month to month", [(9, 16, "CATEGORY")]),

    # -- top_category --
    ("top expense areas this month", [(18, 28, "DATE")]),
    ("show top categories on hdfc card", [(23, 27, "CARD")]),
    ("top spending categories this month", [(24, 34, "DATE")]),
    ("where does most money go on sbi card", [(28, 31, "CARD")]),
    ("biggest categories last month", [(19, 29, "DATE")]),

    # -- spending_health --
    ("am I overspending on food", [(21, 25, "CATEGORY")]),
    ("is my food spending too high", [(6, 10, "CATEGORY")]),

    # -- frequent_merchant --
    ("frequent merchants on hdfc card", [(22, 26, "CARD")]),
    ("top merchants on sbi card this month", [(17, 20, "CARD"), (26, 36, "DATE")]),

    # -- unusual_spend --
    ("unusual transactions on hdfc card", [(24, 28, "CARD")]),
    ("any suspicious charges on sbi card", [(26, 29, "CARD")]),
    ("any spending anomalies this month", [(23, 33, "DATE")]),

    # -- weekly_summary --
    ("weekly spending on food", [(19, 23, "CATEGORY")]),
    ("weekly spending on hdfc card", [(19, 23, "CARD")]),
    ("how much on sbi card this week", [(12, 15, "CARD"), (21, 30, "DATE")]),
    ("this week's grocery expenses", [(0, 9, "DATE"), (12, 19, "CATEGORY")]),
]

# ---------------------------------------------------------------------------
# Known merchants (from categories.py keywords) for entity dictionary
# ---------------------------------------------------------------------------

KNOWN_MERCHANTS = [
    # ── Food Delivery Apps ────────────────────────────────────────────────
    "swiggy", "zomato", "eatsure", "dunzo", "dineout", "magicpin",
    "box8", "freshmenu", "eatclub", "blinkit bistro", "zepto cafe",
    # ── Restaurant Chains ─────────────────────────────────────────────────
    "dominos", "mcdonald", "kfc", "burger king", "pizza hut",
    "starbucks", "subway", "cafe coffee day", "haldiram",
    "barbeque nation", "wow momo", "third wave coffee", "blue tokai",
    "baskin robbins", "taco bell", "dunkin", "popeyes", "tim hortons",
    "saravana bhavan", "theobroma", "biryani by kilo", "sagar ratna",
    "bikanervala", "a2b",
    # Cloud kitchens (Rebel Foods)
    "faasos", "behrouz biryani", "oven story", "lunchbox",
    # ── Groceries & Quick Commerce ────────────────────────────────────────
    "bigbasket", "blinkit", "dmart", "zepto", "instamart", "jiomart",
    "grofers", "nature basket", "amazon fresh", "flipkart minutes",
    "country delight", "licious", "freshtohome", "milkbasket",
    "bbdaily", "spencers", "akshayakalpa", "eggoz",
    # ── Shopping & Ecommerce ──────────────────────────────────────────────
    "amazon", "myntra", "flipkart", "ajio", "meesho", "nykaa",
    "tata cliq", "tata neu", "shoppers stop", "h&m", "zara", "uniqlo",
    "decathlon", "ikea", "croma", "vijay sales", "reliance digital",
    "firstcry", "lenskart", "snapdeal", "pepperfry", "urban ladder",
    "indiamart",
    # D2C brands
    "boat", "mamaearth", "noise", "sugar cosmetics", "bewakoof",
    "the souled store", "wakefit", "mcaffeine", "minimalist",
    "healthkart", "snitch", "mokobara", "urban company",
    # ── Transportation & Mobility ─────────────────────────────────────────
    "uber", "ola", "rapido", "irctc", "metro",
    "blusmart", "namma yatri", "indrive", "meru", "blablacar",
    "yulu", "bounce", "dmrc", "bmrcl", "fastag", "park+",
    "redbus", "abhibus", "ixigo",
    # ── Entertainment — Video Streaming ───────────────────────────────────
    "netflix", "spotify", "hotstar", "jiohotstar", "youtube",
    "amazon prime", "sonyliv", "zee5", "youtube premium",
    "mx player", "aha", "sun nxt", "hoichoi", "altbalaji",
    "apple tv", "apple music", "disney",
    # Entertainment — Music
    "jiosaavn", "gaana", "wynk music", "amazon music",
    # Entertainment — Gaming & Fantasy Sports
    "dream11", "mpl", "winzo", "zupee", "my11circle",
    "google play", "steam",
    # Entertainment — Events & Tickets
    "bookmyshow", "pvr", "inox", "paytm insider",
    # ── Health & Medical ──────────────────────────────────────────────────
    "apollo", "medplus", "netmeds", "pharmeasy", "1mg", "cult.fit",
    "tata 1mg", "truemeds", "practo", "medibuddy",
    "healthifyme", "lybrate", "healthians",
    # Diagnostics & Hospitals
    "dr lal pathlabs", "srl diagnostics", "thyrocare", "metropolis",
    "fortis", "max healthcare", "manipal hospitals", "narayana health",
    # Insurance
    "star health", "hdfc ergo", "acko", "clove dental",
    # ── Utilities & Bills ─────────────────────────────────────────────────
    "jio", "airtel", "vodafone", "bsnl", "mtnl",
    "act fibernet", "hathway", "tata play", "dish tv",
    "d2h", "sun direct", "excitel", "jio fiber", "airtel fiber",
    # Electricity boards
    "bescom", "msedcl", "tpddl", "bses", "cesc", "kseb", "tangedco",
    "uppcl", "pspcl", "tata power",
    # Gas & Water
    "igl", "mgl", "adani gas",
    # ── Travel ────────────────────────────────────────────────────────────
    "oyo", "makemytrip", "goibibo", "cleartrip", "yatra",
    "airbnb", "booking.com", "indigo", "air india", "spicejet", "vistara",
    "easemytrip", "agoda", "trip.com", "thomas cook", "sotc",
    "thrillophilia", "zoomcar", "savaari", "stayvista", "saffronstays",
    # ── Education ─────────────────────────────────────────────────────────
    "udemy", "coursera", "byju", "kindle", "audible", "skillshare",
    "unacademy", "physicswallah", "vedantu", "testbook", "adda247",
    "toppr", "allen", "aakash", "upgrad", "scaler", "great learning",
    "simplilearn", "coding ninjas", "masai school", "whitehat jr",
    "cuemath", "duolingo", "linkedin learning",
    # ── Finance & Investment ──────────────────────────────────────────────
    "groww", "zerodha", "upstox", "paytm", "google pay", "phonepe",
    "angel one", "5paisa", "kuvera", "indmoney", "paytm money",
    "icici direct", "hdfc securities", "motilal oswal",
    # BNPL & Pay Later
    "cred", "simpl", "lazypay", "bajaj finserv", "slice", "uni cards",
    "amazon pay", "freecharge",
    # Neo-banks & Lending
    "jupiter", "fi money", "niyo", "freo", "open",
    "kreditbee", "earlysalary", "mpokket", "navi", "dhani",
    "home credit", "moneyview", "mobikwik",
    # Insurance & Crypto
    "policybazaar", "digit insurance", "jar",
    "wazirx", "coindcx", "coinswitch", "zebpay",
    # Payment Gateways (appear as prefixes in statements)
    "razorpay", "billdesk", "cashfree", "ccavenue", "instamojo",
]

# ---------------------------------------------------------------------------
# Known categories (matching the 12 in the app)
# ---------------------------------------------------------------------------

KNOWN_CATEGORIES = [
    "food and dining", "food", "dining", "restaurant",
    "groceries", "grocery",
    "shopping",
    "transportation", "transport", "fuel",
    "entertainment",
    "health and medical", "health", "medical",
    "utilities and bills", "utilities", "bills",
    "travel",
    "education",
    "finance and investment", "finance", "investment",
    "transfers", "transfer",
    "other",
]

# Map short forms to canonical category names
CATEGORY_CANONICAL = {
    "food": "Food & Dining",
    "dining": "Food & Dining",
    "restaurant": "Food & Dining",
    "food and dining": "Food & Dining",
    "grocery": "Groceries",
    "groceries": "Groceries",
    "shopping": "Shopping",
    "transportation": "Transportation",
    "transport": "Transportation",
    "fuel": "Transportation",
    "entertainment": "Entertainment",
    "health": "Health & Medical",
    "medical": "Health & Medical",
    "health and medical": "Health & Medical",
    "utilities": "Utilities & Bills",
    "bills": "Utilities & Bills",
    "utilities and bills": "Utilities & Bills",
    "travel": "Travel",
    "education": "Education",
    "finance": "Finance & Investment",
    "investment": "Finance & Investment",
    "finance and investment": "Finance & Investment",
    "transfers": "Transfers",
    "transfer": "Transfers",
    "other": "Other",
}

# ---------------------------------------------------------------------------
# Known card issuers / bank names for entity dictionary
# ---------------------------------------------------------------------------

KNOWN_CARDS = [
    # Indian banks
    "sbi", "hdfc", "icici", "axis", "kotak", "indusind", "yes bank",
    "rbl", "bob", "canara", "pnb", "idbi", "federal", "bandhan",
    "au small finance", "idfc first", "hsbc india",
    "standard chartered", "union bank", "bank of india", "indian bank",
    "central bank of india", "south indian bank", "karnataka bank", "dbs",
    # US banks
    "chase", "bofa", "wells fargo", "citi", "capital one", "amex",
    "discover", "us bank", "barclays us", "synchrony",
    # UK banks
    "barclays", "hsbc", "lloyds", "natwest", "santander uk",
    "monzo", "revolut", "starling",
    # Networks / generic
    "visa", "mastercard", "rupay", "diners",
    # Common abbreviations
    "hdfc bank", "icici bank", "sbi card", "axis bank", "kotak mahindra",
    "bank of america", "american express", "capital one card",
    "yes bank card", "bob card", "pnb card",
    "union bank of india", "south indian bank card", "dbs bank",
    "standard chartered card", "karnataka bank card",
]

# Map spoken forms → canonical issuer names
CARD_CANONICAL = {
    # Indian banks
    "sbi": "SBI",
    "sbi card": "SBI",
    "state bank": "SBI",
    "hdfc": "HDFC",
    "hdfc bank": "HDFC",
    "hdfc credit": "HDFC",
    "icici": "ICICI",
    "icici bank": "ICICI",
    "axis": "Axis",
    "axis bank": "Axis",
    "kotak": "Kotak",
    "kotak mahindra": "Kotak",
    "indusind": "IndusInd",
    "yes bank": "Yes Bank",
    "yes bank card": "Yes Bank",
    "rbl": "RBL",
    "bob": "BOB",
    "bob card": "BOB",
    "bank of baroda": "BOB",
    "canara": "Canara",
    "pnb": "PNB",
    "pnb card": "PNB",
    "punjab national bank": "PNB",
    "idbi": "IDBI",
    "federal": "Federal",
    "bandhan": "Bandhan",
    "au small finance": "AU Small Finance",
    "idfc first": "IDFC First",
    "idfc": "IDFC First",
    # US banks
    "chase": "Chase",
    "bofa": "Bank of America",
    "bank of america": "Bank of America",
    "wells fargo": "Wells Fargo",
    "citi": "Citi",
    "citibank": "Citi",
    "capital one": "Capital One",
    "capital one card": "Capital One",
    "amex": "Amex",
    "american express": "Amex",
    "discover": "Discover",
    "us bank": "US Bank",
    "barclays us": "Barclays",
    "synchrony": "Synchrony",
    # Additional Indian banks (from bank_credit_cards.csv)
    "standard chartered": "Standard Chartered",
    "sc": "Standard Chartered",
    "union bank": "Union Bank",
    "union bank of india": "Union Bank",
    "bank of india": "Bank of India",
    "boi": "Bank of India",
    "indian bank": "Indian Bank",
    "central bank": "Central Bank of India",
    "central bank of india": "Central Bank of India",
    "south indian bank": "South Indian Bank",
    "sib": "South Indian Bank",
    "karnataka bank": "Karnataka Bank",
    "dbs": "DBS",
    "dbs bank": "DBS",
    # UK banks
    "barclays": "Barclays",
    "hsbc": "HSBC",
    "hsbc india": "HSBC",
    "lloyds": "Lloyds",
    "natwest": "NatWest",
    "santander uk": "Santander",
    "santander": "Santander",
    "monzo": "Monzo",
    "revolut": "Revolut",
    "starling": "Starling",
}
